# Generated by Django 5.2.1 on 2025-05-27 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/pimage')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.brand')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.category')),
                ('sub_cetegory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eshop.subcategory')),
            ],
        ),
    ]
