# Generated by Django 5.2.1 on 2025-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_product_pre_price_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pre_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
    ]
