# Generated by Django 5.1.4 on 2025-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_product_pre_price_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_cetegory',
            new_name='sub_category',
        ),
    ]
