# Generated by Django 5.1.4 on 2025-07-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_alter_slider_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
