# Generated by Django 5.1.4 on 2025-07-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_order_date_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=150),
        ),
    ]
