# Generated by Django 5.2.1 on 2025-07-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
